before_install:
  - ci/install-stack.sh --os ${TRAVIS_OS_NAME} --verbose

cache:
  directories:
    - ${HOME}/.local/bin
    - .stack-root
    - .stack-work
  timeout: 1000

deploy:
  - file: .build/${TRAVIS_OS_NAME}/bintray.json
    key:
      secure: EaX5OWSCJcAB/yRhEWDDZ9dDM9HXzDnyLdWCeLDKpd82X4xSMP9RXvxOSyXm3xCeZZtt+WwPjcfwBBgeVfcmBfUhhfAVDqlToo+Y6WhUDincaaMC77/f6Yq7LP+Bx6eJelUgpaygbiqH2jR2xzEdVPyDYC/npjcVyR96JUK8k5Oj7GmIbkwr2tzAM8cgDJHY2VwR0PeObLK+t1CEAcaYhb6JJ7yPDCr3vPTl6IgUOqGmkaA/gwO7Fx6wFm+HwSEXVWUfz3NHssHUt6tQHv0AjoDLK84v2DBH1hSqYUEEJqr+5dE26k4G0t2BZJnYkzIgu6YO4qGAvtF8PnH//uKcwiJXwZViheCjnPe/h7Kl/RVGms37jbeCOZWKMro5kZosTWjAlT+P5v1C4650MObU4k0SPFmqiT25GEUDZhsy9sc9jWo+Yo7a31jqcCKcAO9PvUQCvxgChV1sV2Bq3axmnI0O2U/9VsskEQQj0pm8VygqC43gTdquVKNu88+c2OnpoZkXrQK6x/34vA97bFkSl2JWIxefXoJ3wKalcd5vp+HcQvm/TAnaYcHAt7ju2P/KRrY1zTo+mLlIX3DNXWfNxjHHJRIwPRuEohxa1vgwjajKv5dKkwDOrXYhC33AEkq06Sgl2jdV3ZoR6U2MaFGi9QcWAkEvBP5DYbboTvFzrOU=
    on:
      repo: joneshf/purty
      tags: true
    provider: bintray
    skip_cleanup: true
    user: joneshf

env:
  global:
    - PATH=/usr/local/opt/coreutils/libexec/gnubin:${PATH}
    - STACK_ROOT=${TRAVIS_BUILD_DIR}/.stack-root

install:
  - stack setup

language: c

notifications:
  webhooks:
    on_start: always
    urls:
      - secure: e26AJAtbrYJYHk8gBc79rRDq6rgnq11AgU7lXyps9Dt+22FfP7wMZgOFvY0ECyz9qyy0+6p/+Qmi7DUVTOMJl+IHJlUiH1bKxDYEphPro5Npz3Zx8zkJXqNuoPN0QqMxW8ca7z/afHVD2qAiyobxdTaqyj/25M9FYf4zRzSCcnNqrUkMwpNTYKf+mut8cmHgEQovh5cLXU/XSBHq9yQpjhy0uAlmUfchSsUSvykymSW9VR4GxINJMp4HopzhK1CMSzFAUI0vFIYyfO3l9FeEXJh80uU/dGhx8ajEv/a/6f9Nt/BxBW5AHlW4m5a3AT5M2OC38/OXy0rqVo+cMDhNTXWIJ9B6ugkgm2RZkBtNtO1SmtlYCIGE2hTnXCRLMOI8DNFvnrLQNlYJYBaspj2lF0rk1mu4Awf0XYNrIN+iQPSTUpiF3dwMic8M8fcHCzkTXhIwa/lA5vuJiMW8HtCqtSpqcyxsYpngOP/8s1ZVG64IhJwDPz2rYS40TpcE8kuxusysQ7Pi9vGbndpOVr8MQ5ePcD3779yS6nIrvYwb3XqUUSUpuMZ4eOyyZa40vpYt+wzDUi4uODOWwK6v5CPMIhncm3svjEj88UhOF95ee+4FBxABKcHJ3ZRVt7ifweKAx6/Q04VyGYDV6yeoLbPHCKUsDPadpFuIJmaCBhWx7Y4=

os:
  - linux
  - osx

sudo: false

script:
  - make bootstrap OS=${TRAVIS_OS_NAME}
  - "[ dependencies = ${BUILD_TYPE} ] || make --jobs bintray-artifacts test OS=${TRAVIS_OS_NAME} VERSION_PURTY=${TRAVIS_TAG}"
